name: bigboxx
base: core18
version: git
summary: IoT middleware from e-Cattle platform for livestock farms
description: |
  e-Cattle BigBoxx is a middleware to receive, rank, segment, persist and provide sensory data
  for IoT applications in livetstock farms. 

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

environment:
  SNAPCRAFT_ENABLE_DEVELOPER_DEBUG: "yes"

apps:
  start:
#    command: kernel
    command: sh -c "cd $SNAP/kernel && node ./bin/server.js"
    passthrough:
      autostart: start
    plugs: [home, network, network-bind]

parts:
  kernel:
    plugin: nodejs
    nodejs-package-manager: npm
    source: https://github.com/e-cattle/kernel.git
    source-branch: master
    source-depth: 1
    override-build: |
      snapcraftctl build
      echo "Moving from $(pwd) to $SNAPCRAFT_PART_INSTALL/kernel"
      mkdir -p $SNAPCRAFT_PART_INSTALL/kernel
      mv * $SNAPCRAFT_PART_INSTALL/kernel/
  
#  api:
#    plugin: nodejs
#    source: https://github.com/e-cattle/api.git
#    source-branch: master
#    source-depth: 1
#    override-build: |
#      snapcraftctl build
#      echo "Moving from $(pwd) to $SNAPCRAFT_PART_INSTALL/api"
#      mkdir -p $SNAPCRAFT_PART_INSTALL/api
#      mv -R * $SNAPCRAFT_PART_INSTALL/api/
  
#  manager:
#    plugin: nodejs
#    source: https://github.com/e-cattle/manager.git
#    source-branch: master
