name: bigboxx
base: core18
version: git
summary: IoT middleware from e-Cattle platform for livestock farms
description: |
  e-Cattle BigBoxx is a middleware to receive, rank, segment, persist and provide sensory data
  for IoT applications in livetstock farms. 

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

environment:
  SNAPCRAFT_ENABLE_DEVELOPER_DEBUG: "yes"

apps:
  kernel:
    command: sh -c "nohup node $SNAP/kernel/bin/server.js > /dev/null 2>&1 &"
    plugs: [home, network, network-bind]
  
  api:
    command: sh -c "nohup node $SNAP/api/bin/server.js > /dev/null 2>&1 &"
    plugs: [home, network, network-bind]

parts:
  kernel:
    plugin: nodejs
    nodejs-package-manager: npm
    source: https://github.com/e-cattle/kernel.git
    source-branch: master
    source-depth: 1
    filesets:
      exclude: [-src,-bin,-node_modules,-package]
    stage: [$exclude]
    prime: [$exclude]
    organize:
      README.md: README.md-kernel
      package.json: package.json-kernel
      package-lock.json: package-lock.json-kernel
    override-build: |
      snapcraftctl build
      echo "Moving from $(pwd) to $SNAPCRAFT_PART_INSTALL/kernel"
      mkdir -p $SNAPCRAFT_PART_INSTALL/kernel
      mv * $SNAPCRAFT_PART_INSTALL/kernel/
  
  api:
    plugin: nodejs
    nodejs-package-manager: npm
    source: https://github.com/e-cattle/api.git
    source-branch: master
    source-depth: 1
    override-build: |
      snapcraftctl build
      echo "Moving from $(pwd) to $SNAPCRAFT_PART_INSTALL/api"
      mkdir -p $SNAPCRAFT_PART_INSTALL/api
      mv * $SNAPCRAFT_PART_INSTALL/api/
  
#  manager:
#    plugin: nodejs
#    source: https://github.com/e-cattle/manager.git
#    source-branch: master
