name: bigboxx
base: core18
version: git
summary: IoT middleware from e-Cattle platform for livestock farms
description: |
  e-Cattle BigBoxx is a middleware to receive, rank, segment, persist and provide sensory data
  for IoT applications in livetstock farms. 

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

environment:
  SNAPCRAFT_ENABLE_DEVELOPER_DEBUG: "yes"

apps:
  mongo:
    command: env LC_ALL=C mongod --bind_ip 0.0.0.0 --port=27017 --pidfilepath $SNAP_USER_DATA/mongod.pid --journal --dbpath $SNAP_USER_DATA/mongo
    daemon: simple

  kernel:
    command: node $SNAP/kernel/bin/server.js > $SNAP_USER_DATA/kernel.log
    daemon: simple
  
  api:
    command: node $SNAP/api/bin/server.js > $SNAP_USER_DATA/api.log
    daemon: simple
  
#  backup:
#    command: mongodump --db ecattle-kernel --archive

hooks:
  install:
    plugs: [home, network, network-bind]

plugs:
  home:
  network:
  network-bind:

parts:
  kernel:
    plugin: nodejs
    nodejs-package-manager: npm
    stage-packages:
      - mongodb-server
    source: https://github.com/e-cattle/kernel.git
    source-branch: master
    source-depth: 1
    filesets:
      exclude: [-src,-bin,-node_modules,-package]
    stage: [$exclude]
    prime: [$exclude]
    organize:
      README.md: README.md-kernel
      package.json: package.json-kernel
      package-lock.json: package-lock.json-kernel
    override-build: |
      snapcraftctl build
      echo "Moving from $(pwd) to $SNAPCRAFT_PART_INSTALL/kernel..."
      mkdir -p $SNAPCRAFT_PART_INSTALL/kernel
      cp -r * $SNAPCRAFT_PART_INSTALL/kernel/
      rm -rf * > /dev/null
  
  api:
    plugin: nodejs
    nodejs-package-manager: npm
    source: https://github.com/e-cattle/api.git
    source-branch: master
    source-depth: 1
    filesets:
      exclude: [-src,-bin,-node_modules,-package]
    stage: [$exclude]
    prime: [$exclude]
    organize:
      README.md: README.md-api
      package.json: package.json-api
      package-lock.json: package-lock.json-api
    override-build: |
      snapcraftctl build
      echo "Moving from $(pwd) to $SNAPCRAFT_PART_INSTALL/api..."
      mkdir -p $SNAPCRAFT_PART_INSTALL/api
      cp -r * $SNAPCRAFT_PART_INSTALL/api/
      rm -rf *  > /dev/null
  
#  manager:
#    plugin: nodejs
#    source: https://github.com/e-cattle/manager.git
#    source-branch: master
